name: Markdown Linter

on:
  push:
    branches: [main]
    paths:
      - '**.md'
  pull_request:
    branches: [main]
    paths:
      - '**.md'
permissions:
  contents: read

jobs:
  linter:
    if: (github.repository == 'yuluo-yx/typo')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./tools/github-setup-deps
      - run: make install-markdownlint
      - run: make markdown-lint
